### ISSUE TITLE
Issue with Count By

### ISSUE THREAD

**Issue by rajnish07** [greatfrontend/greatfrontend#105]
## Your GreatFrontEnd account email (optional)

rajnishtb@gmail.com 

## Problematic section

Missing test cases which allows user to submit incorrect solution.

- [ ] Test Cases (Missing)
-  Not all test cases cover this requirement in the question.

-      Strings: The property of an object. E.g. 'length' can be used to return the number of elements of arrays.

## Type of question

- [ ] JavaScript

## Describe the issue

When the iteratees is a string is supposed to be work as a property of an object. But if user only uses the length attribute all of the test cases pass including the ones when submit is clicked.

## Code you used to submit (where relevant)

# Incorrect solution
```js
    let val;
    if(typeof iteratee === 'string') {
      val = item.length;
    } else {
      val = iteratee(item);
    }
```

Rather the acceptable solution should be

# Correct solution
```js
    let val;
    if(typeof iteratee === 'string') {
      val = item[iteratee];
    } else {
      val = iteratee(item);
    }
```

## Expected behavior vs Actual behavior (where relevant)

A test case like below should be added to prevent the user to submit incorrect solution.
```js
  test('property iteratees 2', () => {
    expect(countBy([{name: 'Developer 1', age: 21}, {name: 'Developer 2', age: 25}, {name: 'Developer 3', age: 21}], 'age')).toEqual({ 21: 2 , 25: 1});
  });
```

## Screenshots (where relevant)

<img width="845" alt="Screenshot 2024-01-17 at 6 58 59 PM" src="https://github.com/greatfrontend/greatfrontend/assets/40293642/2b9504f7-54c9-458a-adde-6de6dd7585a7">

**Comment by feilinlp** [comment]
Thank you for pointing this out! However, we decided to only allow functions for iteratee in ...By questions for now.
