### ISSUE TITLE
Typo in  News Feed (e.g. Facebook) System Design question

### ISSUE THREAD

**Issue by felipeS** [greatfrontend/greatfrontend#125]
## Your GreatFrontEnd account email (optional)

pipelon54@gmail.com 

## Problematic section

- [ ] Question Description
- [ ] Question Skeleton
- [x] Question Solution
- [ ] Test Cases (Missing/Incorrect/Unclear)

## Type of question

- [ ] JavaScript
- [ ] User Interface
- [x] System Design
- [ ] Quiz

## Describe the issue

The text is missing the connector:

_Clients can try be smart and de-duplicate posts by not showing posts that are already visible._ 

## Expected behavior vs Actual behavior (where relevant)

_Clients can try **to** be smart and de-duplicate posts by not showing posts that are already visible._ 

## Screenshots (where relevant)

<img width="856" alt="image" src="https://github.com/greatfrontend/greatfrontend/assets/2282421/abecfb0b-ec7d-4b2c-8c9a-2f9b4b76e603">

**Comment by feilinlp** [comment]
Thank you! It is fixed and will be deployed soon.
