### ISSUE TITLE
Issue with Squash Object

### ISSUE THREAD

**Issue by allanloji** [greatfrontend/greatfrontend#127]
## Your GreatFrontEnd account email (optional)

allanloji@gmail.com 

## Problematic section

- [x] Question Description
- [ ] Question Skeleton
- [ ] Question Solution
- [ ] Test Cases (Missing/Incorrect/Unclear)

## Type of question

- [x] JavaScript
- [ ] User Interface
- [ ] System Design
- [ ] Quiz

## Describe the issue
On the examples on the description for Empty Keys there is an extra character in the nest object key (1bar), so the solution is not correct

### Expected

```javascript
const object = {
  foo: {
    '': { '': 1, bar: 2 },
  },
};
squashObject(object); // { foo: 1, 'foo.bar': 2 }
```

### Actual 

```javascript
const object = {
  foo: {
    '': { '': 1, 1bar: 2 },
  },
};
squashObject(object); // { foo: 1, 'foo.bar': 2 }
```

## Screenshots (where relevant)

![image](https://github.com/greatfrontend/greatfrontend/assets/33562292/4948be7b-3a5e-4204-b51a-4c7e40f22580)

**Comment by feilinlp** [comment]
Thank you for pointing it out! We have fixed it and it'll be deployed soon.
