### ISSUE TITLE
Issue with Explain `Function.prototype.bind`

### ISSUE THREAD

**Issue by michelleshafrir** [greatfrontend/greatfrontend#13]
## Your GreatFrontEnd account email (optional)

m.shafrir5@gmail.com 

## Problematic section

- [ ] Question Description
- [ ] Question Skeleton
- [X] Question Solution
- [ ] Test Cases (Missing/Incorrect/Unclear)

## Type of question

- [X] JavaScript
- [ ] User Interface
- [ ] System Design
- [ ] Quiz

## Describe the issue

The final line of the code snippet has a comment implying the result should be 42 when really it should be 21 as the this in getAge is now bound to the mary object

## Code you used to submit (where relevant)

N/A

## Expected behavior vs Actual behavior (where relevant)
Expected:
```console.log(boundGetAgeMary()); // 21```
the code in the page now says:
```console.log(boundGetAgeMary()); // 42```

## Anything else?

Thanks for building this site! It's been a great resource so far!

**Comment by gfeeng** [comment]
We've fixed this: https://www.greatfrontend.com/questions/quiz/javascript/explain-function-prototype-bind! Thank you!

**Comment by Franklinelvis** [comment]
Hello I hope you are having a good day
