### ISSUE TITLE
Issue with Binary Search

### ISSUE THREAD

**Issue by efrymire** [greatfrontend/greatfrontend#130]
## Your GreatFrontEnd account email (optional)

ellie.frymire@gmail.com 

## Problematic section

- [x] Question Description
- [ ] Question Skeleton
- [ ] Question Solution
- [ ] Test Cases (Missing/Incorrect/Unclear)

## Type of question

- [x] JavaScript
- [ ] User Interface
- [ ] System Design
- [ ] Quiz

## Describe the issue

The description says:
> _Implement a function that performs binary search on an array of numbers. The function should take in a sorted array of integers and a target integer to find. It returns the index of the target element or -1, if the target element doesn't exist in the array._

But the examples section includes a non-sorted array: 
```
binarySearch([1, 2, 3, 6, 9, 11], 6); // 3
binarySearch([1, 2, 3, 12, 16, 14], 5); // -1
```

The second array should instead be `[1, 2, 3, 12, 14, 16]` since the question assumes a sorted array. 
The assumption could be sorted descending or ascending, but this is neither. 

## Code you used to submit (where relevant)

```js
/**
 * @param {Array<*|Array>} value
 * @return {Array}
 */
export default function flatten(value) {
  // Your code here.
}
```

**Comment by yangshun** [comment]
cc @feilinlp

**Comment by feilinlp** [comment]
Thank you for pointing it out! It is fixed and will be deployed soon
