### ISSUE TITLE
Issue with Deep Clone

### ISSUE THREAD

**Issue by brunomperes** [greatfrontend/greatfrontend#14]
## Problematic section

- [x] Question Description
- [ ] Question Skeleton
- [x] Question Solution
- [ ] Test Cases (Missing/Incorrect/Unclear)

## Type of question

- [x] JavaScript
- [ ] User Interface
- [ ] System Design
- [ ] Quiz

## Describe the issue

The snippet in the problem description doesn't execute:

```js
const obj1 = { user: { role: 'admin' } };
const clonedObj1 = deepClone(foo);

clonedObj1.user.role = 'guest'; // Change the cloned user's role to 'guest'.
clonedObj1.user.role; // 'guest'
obj1.user.role; // Should still be 'admin'.

const obj2 = { foo: [{ bar: 'baz' }] };
const clonedObj2 = deepClone(obj);

obj2.foo[0].bar = 'bax'; // Modify the original object.
obj2.foo[0].bar; // 'bax'
clonedObj2.foo[0].bar; // Should still be 'baz'.
```

I guess should probably be:
```diff
const obj1 = { user: { role: 'admin' } };
- const clonedObj1 = deepClone(foo);
+ const clonedObj1 = deepClone(obj1);

clonedObj1.user.role = 'guest'; // Change the cloned user's role to 'guest'.
clonedObj1.user.role; // 'guest'
obj1.user.role; // Should still be 'admin'.

const obj2 = { foo: [{ bar: 'baz' }] };
- const clonedObj2 = deepClone(obj);
+ const clonedObj2 = deepClone(obj2);

obj2.foo[0].bar = 'bax'; // Modify the original object.
obj2.foo[0].bar; // 'bax'
clonedObj2.foo[0].bar; // Should still be 'baz'.
```

There seems to be a small typo in the solution text as well:

> With the `for ... in` statement, inherited enumerable properties are be processed as well. 

With the `for ... in` statement, inherited enumerable properties are ~be~ processed as well. 

## Code you used to submit (where relevant)

N/A

## Anything else?

Not really, thanks :)

**Comment by gfeeng** [comment]
This has been fixed. Thank you @brunomperes for your feedback as always!
