### ISSUE TITLE
Issue with News Feed (e.g. Facebook)

### ISSUE THREAD

**Issue by Zhencha0Cai** [greatfrontend/greatfrontend#15]
## Problematic section

- [ ] Question Description
- [ ] Question Skeleton
- [x] Question Solution
- [ ] Test Cases (Missing/Incorrect/Unclear)

## Type of question

- [ ] JavaScript
- [ ] User Interface
- [x] System Design
- [ ] Quiz

## Describe the issue
Under Multilingual Timestamps, point 3. Modern browsers can leverage `Intl.DateFormFormat()` API to transform a raw timestamp into a translated datetime string. Seems like there is a type.
`Intl.DateFormFormat()`  should be `Intl.DateTimeFormat()`

**Comment by gfeeng** [comment]
Thank you @Zhencha0Cai, this has been fixed!
