### ISSUE TITLE
Issue with Photo Sharing (e.g. Instagram), filter name present twice

### ISSUE THREAD

**Issue by shivamgupta08** [greatfrontend/greatfrontend#150]
https://www.greatfrontend.com/questions/system-design/photo-sharing-instagram#filters
Contrast filter is mentioned twice instead of brightness.

## Your GreatFrontEnd account email (optional)

sgshivamgupta14@gmail.com 

## Problematic section

- [ ] Question Description
- [ ] Question Skeleton
- [x] Question Solution
- [ ] Test Cases (Missing/Incorrect/Unclear)

## Type of question

- [ ] JavaScript
- [ ] User Interface
- [x] System Design
- [ ] Quiz

## Code you used to submit (where relevant)

```js
/**
 * @param {Array<*|Array>} value
 * @return {Array}
 */
export default function flatten(value) {
  // Your code here.
}
```

**Comment by yangshun** [comment]
Fixed! Thanks!
