### ISSUE TITLE
Issue with Explain your understanding of the box model and how you would tell the browser in CSS to render your layout in different box models.

### ISSUE THREAD

**Issue by amanmehta25** [greatfrontend/greatfrontend#17]
## Your GreatFrontEnd account email (optional)

amanxmehta@gmail.com 

## Problematic section

- [ ] Question Description
- [ ] Question Skeleton
- [x] Question Solution
- [ ] Test Cases (Missing/Incorrect/Unclear)

## Type of question

- [ ] JavaScript
- [ ] User Interface
- [ ] System Design
- [x] Quiz

## Describe the issue

There is a typo in the reference link in the last section named `Extra`.

## Expected behavior vs Actual behavior (where relevant)

Currently the [link](https://www.greatfrontend.com/quiz/css/what-does-box-sizing-border-box-do-what-are-its-advantages) is redirecting to `Page Not Found`. It should be this [link](https://www.greatfrontend.com/questions/quiz/css/what-does-box-sizing-border-box-do-what-are-its-advantages) which is a valid URL.
## Screenshots (where relevant)

<img width="948" alt="Screenshot 2022-12-19 at 1 34 32 PM" src="https://user-images.githubusercontent.com/11312312/208376771-df5105eb-bf6f-4230-bb5d-710fdd002540.png">

**Comment by gfeeng** [comment]
This has been fixed! https://www.greatfrontend.com/questions/quiz/css/explain-your-understanding-of-the-box-model-and-how-you-would-tell-the-browser-in-css-to-render-your-layout-in-different-box-models
