### ISSUE TITLE
Issue with CSS display quiz

### ISSUE THREAD

**Issue by AlessandroRoic** [greatfrontend/greatfrontend#18]
## Problematic section

- [ ] Question Description
- [ ] Question Skeleton
- [x] Question Solution
- [ ] Test Cases (Missing/Incorrect/Unclear)

## Type of question

- [ ] JavaScript
- [ ] User Interface
- [ ] System Design
- [x] Quiz

## Describe the issue
Question [What is the CSS `display` property and can you give a few examples of its use?](https://www.greatfrontend.com/questions/quiz/css/what-is-the-css-display-property-and-can-you-give-a-few-examples-of-its-use) is missing some values and descriptions.

It provides some values that display can have
> The various values for the display property: none, block, inline, inline-block, flex, grid, table, table-row, table-cell, list-item.

Including flex and grid, but it doesn't list them in the table below:
![image](https://user-images.githubusercontent.com/29387855/209322834-6f789be9-cdfa-49b8-8c01-afee7023b293.png)

Also it could be improved by adding all values [ from here](https://developer.mozilla.org/en-US/docs/Web/CSS/display).

**Comment by gfeeng** [comment]
Included `flex` and `grid` 🎉
