### ISSUE TITLE
Any plans to offer `reset` functionality for css challenges?

### ISSUE THREAD

**Issue by lancej1022** [greatfrontend/greatfrontend#2]
Ive noticed that the JS challenges have a reset button which I make a lot of use of, but the css/UI challenges don't have this functionality, forcing me to manually delete my code after Im done attempting the problem. Hardly the end of the world, but it would be great to have a reset button for all types of the challenges.

edit: I do see a "reset to default" option when I refresh the page in the bottom of the UI preview, but it doesn't appear to be present otherwise

**Comment by gfeeng** [comment]
Hi @lancej1022! Absolutely! We're revamping our coding workspace and will add that functionality soon 😃 

> edit: I do see a "reset to default" option when I refresh the page in the bottom of the UI preview, but it doesn't appear to be present otherwise

Was about to suggest this and you found out already, please use this approach in the meantime.

**Comment by gfeeng** [comment]
This has been done!
