### ISSUE TITLE
Issue with getElementsByClassName

### ISSUE THREAD

**Issue by longnt80** [greatfrontend/greatfrontend#22]
## Your GreatFrontEnd account email (optional)

longnt80@gmail.com 

## Problematic section

- [ ] Question Description
- [ ] Question Skeleton
- [ ] Question Solution
- [x] Test Cases (Missing/Incorrect/Unclear)

## Type of question

- [x] JavaScript
- [ ] User Interface
- [ ] System Design
- [ ] Quiz

## Code you used to submit (where relevant)

```js
test('non-existent class names', () => {
    const doc = new DOMParser().parseFromString(
      `<div class="foo">
        <span class="foo>Span</span>
        <p>Paragraph</p>
        <div></div>
      </div>`,
      'text/html',
    );
```

## Expected behavior vs Actual behavior (where relevant)

Just missing a double quote for class `foo` for the span in the HTML above and making the query returns only one element (the `div`). This doesn't fail the test case however it might be confusing due to the `expected.length` returns only `1`.

**Comment by gfeeng** [comment]
Thank you! Has been fixed
