### ISSUE TITLE
Issue with Identical DOM Trees

### ISSUE THREAD

**Issue by longnt80** [greatfrontend/greatfrontend#25]
## Your GreatFrontEnd account email (optional)

longnt80@gmail.com 

## Problematic section

- [ ] Question Description
- [ ] Question Skeleton
- [ ] Question Solution
- [x] Test Cases (Missing/Incorrect/Unclear)

## Type of question

- [x] JavaScript
- [ ] User Interface
- [ ] System Design
- [ ] Quiz

## Describe the issue

The provided solution doesn't cover the case where element nodes have different tag names (ex: `p` vs `div`).

## Code you used to submit (where relevant)

```js

test("different tagnames", () => {
    const treeA = new DOMParser().parseFromString(
      `<div>hello</div>`, 
      "text/html"
    );
    const treeB = new DOMParser().parseFromString(
      `<p>hello</p>`, 
      "text/html"
    );

    expect(isSameTree(treeA.body, treeB.body)).toBe(false);
})
```

## Expected behavior vs Actual behavior (where relevant)

The provided solution should pass the test case above.

**Comment by gfeeng** [comment]
It took a while, but this has finally been fixed, thank you!
