### ISSUE TITLE
Issue with Todo List

### ISSUE THREAD

**Issue by mhughdo** [greatfrontend/greatfrontend#27]
## Your GreatFrontEnd account email (optional)

mhughdo@gmail.com 

## Problematic section

- [ ] Question Description
- [ ] Question Skeleton
- [x] Question Solution
- [ ] Test Cases (Missing/Incorrect/Unclear)

## Type of question

- [x] JavaScript
- [x] User Interface
- [ ] System Design
- [ ] Quiz

## Describe the issue

In the Todo List's solution, on line 18, it should be `$span.textContent = label` not `$newTaskElement.textContent = label` because the text should be added to the span, not the `li` itself.

## Expected behavior vs Actual behavior (where relevant)

Expected
<img width="668" alt="image" src="https://user-images.githubusercontent.com/15611134/212798620-3213c960-e01c-47d8-a1a8-a2507a44b988.png">
Actual
<img width="487" alt="image" src="https://user-images.githubusercontent.com/15611134/212798634-2a301dcf-11b8-4ac5-aab9-20b08a83dc00.png">

**Comment by gfeeng** [comment]
Thank you! Sharp eyes you have, just fixed it 😄
