### ISSUE TITLE
Issue with Explain your understanding of the box model and how you would tell the browser in CSS to render your layout in different box models.

### ISSUE THREAD

**Issue by AlbyIanna** [greatfrontend/greatfrontend#28]
## Problematic section

- [ ] Question Description
- [ ] Question Skeleton
- [x] Question Solution
- [ ] Test Cases (Missing/Incorrect/Unclear)

## Type of question

- [ ] JavaScript
- [ ] User Interface
- [ ] System Design
- [x] Quiz

## Describe the issue

The solution of this question says:

> The dimensions of a block element are calculated by `width`, `height`, `padding`, `border`s, and `margin`s.

This is not entirely true, since the margin is not calculated in the dimensions of a block element. As stated on [an article about The Box Model on MDN Web Docs](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/The_box_model#the_standard_css_box_model):

> The margin is not counted towards the actual size of the box — sure, it affects the total space that the box will take up on the page, but only the space outside the box. The box's area stops at the border — it does not extend into the margin.

## Anything else?

I propose to change this line as follows:

> The dimensions of a box are calculated by `width`, `height`, `padding`, and `border`s. The `margin` is not counted towards the actual size of the box — sure, it affects the total space that the box will take up on the page, but only the space outside the box. The box's area stops at the border — it does not extend into the margin.

And quote MDN Web Docs in the reference.

**Comment by gfeeng** [comment]
Great catch @AlbyIanna, we've fixed it!
