### ISSUE TITLE
Issue with Unique Array

### ISSUE THREAD

**Issue by kmanadkat** [greatfrontend/greatfrontend#3]
## Your GreatFrontEnd account email (optional)

kmanadkat@gmail.com

## Problematic section

- [ ] Question Description
- [ ] Question Skeleton
- [x] Question Solution
- [ ] Test Cases (Missing/Incorrect/Unclear)

## Type of question

- [x] JavaScript
- [ ] User Interface
- [ ] System Design
- [ ] Quiz

## Describe the issue

Question URL: https://www.greatfrontend.com/questions/javascript/unique-array

Minor typo in solution explanation, time complexity for `Array.prototype.includes()` is `O(n)` & if it is called for every elements for array of size `n` it becomes `n * O(n)` operations => `o(n^2)`

<img width="878" alt="Screenshot 2022-11-28 at 3 06 42 PM" src="https://user-images.githubusercontent.com/25281055/204244091-e98e10ab-3f88-42e9-a5af-b21bee4a8414.png">

**Comment by gfeeng** [comment]
Thanks for the report @kmanadkat! Have fixed it 😄
