### ISSUE TITLE
Issue with Camel Case Keys

### ISSUE THREAD

**Issue by edwinork** [greatfrontend/greatfrontend#34]
## Your GreatFrontEnd account email (optional)

edwinork@gmail.com 

## Problematic section

- [x] Question Description
- [ ] Question Skeleton
- [ ] Question Solution
- [ ] Test Cases (Missing/Incorrect/Unclear)

## Type of question

- [x] JavaScript
- [ ] User Interface
- [ ] System Design
- [ ] Quiz

## Describe the issue

At the bottom of the description, in the **Notes** section, it says "You can assume the input is always a valid, plain JavaScript object.", however, some test cases use an array as input. It would be clearer if it said "... plain JavaScript object or array".

## Anything else?

Here is a [question](https://www.greatfrontend.com/questions/javascript/deep-equal) where you do make a distinction between a plain JavaScript object and an array.

**Comment by gfeeng** [comment]
Thank you! This has been fixed
