### ISSUE TITLE
Issue with Like Button

### ISSUE THREAD

**Issue by edwinork** [greatfrontend/greatfrontend#36]
## Your GreatFrontEnd account email (optional)

edwinork@gmail.com 

## Problematic section

- [ ] Question Description
- [x] Question Skeleton
- [ ] Question Solution
- [ ] Test Cases (Missing/Incorrect/Unclear)

## Type of question

- [ ] JavaScript
- [x] User Interface
- [ ] System Design
- [ ] Quiz

## Describe the issue

In React version of the question, inside the file `icons.js` there are three invalid SVG properties: `fill-rule`, `stroke-width`, and `stroke-opacity`. They need to be refactored to camel case to be compatible with React. Currently, the console logs `Invalid DOM property` warnings which can be confusing to the learner.

**Comment by gfeeng** [comment]
This has been fixed! 🎉
