### ISSUE TITLE
Issue with Promise.race

### ISSUE THREAD

**Issue by s4rfy** [greatfrontend/greatfrontend#38]
## Your GreatFrontEnd account email (optional)

john@example.com 

## Problematic section

- [x] Question Description
- [x] Question Skeleton
- [x] Question Solution
- [x] Test Cases (Missing/Incorrect/Unclear)

## Type of question

- [x] JavaScript
- [ ] User Interface
- [ ] System Design
- [ ] Quiz

## Describe the issue

I'm a premium user on lifetime access but am still unable to access the question. It says to purchase a premium subscription.

## Code you used to submit (where relevant)

```js
/**
 * @param {Array<*|Array>} value
 * @return {Array}
 */
export default function flatten(value) {
  // Your code here.
}
```

## Screenshots (where relevant)
![Screenshot 2023-03-03 at 3 59 22 PM](https://user-images.githubusercontent.com/84791085/222697463-3cf22b9b-3674-4b3e-879c-07ee7ef05e6c.png)

**Comment by gfeeng** [comment]
Please send us an email at contact@greatfrontend.com!
