### ISSUE TITLE
Issue with Autocomplete - Typos

### ISSUE THREAD

**Issue by justinhchan** [greatfrontend/greatfrontend#41]
## Your GreatFrontEnd account email

justinhchann@gmail.com

## Problematic section

- [ ] Question Description
- [ ] Question Skeleton
- [x] Question Solution
- [ ] Test Cases (Missing/Incorrect/Unclear)

## Type of question

- [ ] JavaScript
- [ ] User Interface
- [x] System Design
- [ ] Quiz

## Describe the issue

There are some text typos in the [Front End System Design Guidebook  - Autocomplete - Handling concurrent requests/race conditions section](https://www.greatfrontend.com/questions/system-design/autocomplete#handling-concurrent-requestsrace-conditions).

> What happens if the user makes changes to the query while there's a pending network request? If there are multiple pending network requests, we will **need to need to** be mindful not to display results for a previous search query. We cannot rely on **the the** return order of network responses from the server because an earlier request might only be completed later than a request fired later on.

**Suggested change**
> What happens if the user makes changes to the query while there's a pending network request? If there are multiple pending network requests, we will need to be mindful not to display results for a previous search query. We cannot rely on the return order of network responses from the server because an earlier request might only be completed later than a request fired later on.

## Anything else?

There is also a typo in the [Client-only Data section](https://www.greatfrontend.com/system-design/framework#client-only-data) of the The RADIO Framework module. 

> Client-only data, also commonly known as state, is data that only needs to live on the client and **does not have to sent** to the server for writing into the database. Client data can be further broken down into two: 

**Suggested change**
> Client-only data, also commonly known as state, is data that only needs to live on the client and does not have to be sent to the server for writing into the database. Client data can be further broken down into two categories:

**Comment by gfeeng** [comment]
Amazing, thank you so much @justinhchan! We've fixed this :)
