### ISSUE TITLE
Issue with Sum

### ISSUE THREAD

**Issue by Udokah** [greatfrontend/greatfrontend#43]
https://www.greatfrontend.com/questions/javascript/sum
The current solution is not ideal, here is a better suggestion.
Calling `sum()` without any arguments at first breaks it.

```
/**
 * @param {number} number
 * @return {Function}
 */
export default function sum(number) {
  let currSum = 0;
  
  if (this != null) {
    currSum = this.currSum;
  }

  if (number == null) {
    return currSum;
  }

  currSum += number;
  return sum.bind({currSum});
}
```

**Comment by loia5tqd001** [comment]
Could you elaborate more on why it's "not ideal"?

**Comment by feilinlp** [comment]
Hi, thank you for your feedback! We decided to keep it as-is first for now, so there won't be changes.
