### ISSUE TITLE
Issue with Explain how prototypal inheritance works

### ISSUE THREAD

**Issue by ananthtpai** [greatfrontend/greatfrontend#44]
## Your GreatFrontEnd account email (optional)

ananthtpai@gmail.com 

## Problematic section

- [ ] Question Description
- [ ] Question Skeleton
- [x] Question Solution
- [ ] Test Cases (Missing/Incorrect/Unclear)

## Type of question

- [ ] JavaScript
- [ ] User Interface
- [ ] System Design
- [x] Quiz

## Describe the issue
 Prototypal Inheritance is explained using `Object.create`,  according to MDN this is no longer the recommended approach. Here is a snippet from MDN docs

> You may also see some legacy code using [Object.create()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/create) to build the inheritance chain. However, because this reassigns the prototype property and removes the [constructor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/constructor) property, it can be more error-prone, while performance gains may not be apparent if the constructors haven't created any instances yet.

The recommended way is by using `Object.setPrototypeOf(Child.prototype, Parent.prototype);`

[Link](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Inheritance_and_the_prototype_chain)

## Code you used to submit (where relevant)

```js
function Parent() {
  this.name = 'Parent';
}

Parent.prototype.greet = function () {
  console.log('Hello from ' + this.name);
};

function Child() {
  Parent.call(this);
  this.name = 'Child';
}

Object.setPrototypeOf(Child.prototype, Parent.prototype);

const child = new Child();

child.greet();
// hello from Child

child.constructor.name;
// 'Child'
```

**Comment by yangshun** [comment]
This is fixed
