### ISSUE TITLE
Issue with Fill

### ISSUE THREAD

**Issue by leopangchan** [greatfrontend/greatfrontend#50]
## Your GreatFrontEnd account email (optional)

yiupang.ch@gmail.com 

## Problematic section

- [ ] Question Description
- [ ] Question Skeleton
- [ ] Question Solution
- [v] Test Cases (Missing/Incorrect/Unclear)

## Type of question

- [v] JavaScript
- [ ] User Interface
- [ ] System Design
- [ ] Quiz

## Describe the issue

  test('fills array with value from start to end when negative indices are provided', () => {
    const arr = [1, 2, 3];
    expect(fill(arr, '*', -2, -1)).toEqual([1, '*', 3]);
  });

**The expected value didn't fill the array from the start to end.**

  test('fills array with value from start to end when out of range indices are provided', () => {
    const arr = [1, 2, 3];
    expect(fill(arr, '*', 1, 10)).toEqual([1, '*', '*', '*']);
  });

**The array only has three values, but the test result has four.**

**Comment by gina-ng** [comment]
Thank you! This has been fixed!
