### ISSUE TITLE
Issue with Difference

### ISSUE THREAD

**Issue by Mhdez221993** [greatfrontend/greatfrontend#55]
## Your GreatFrontEnd account email (optional)

mhdezcoronado@gmail.com 

## Problematic section

- [ ] Question Description
- [ ] Question Solution

## Type of question

- [ ] JavaScript

## Describe the issue
Your implementation of the `difference` function accepts the `values` parameter as an array (`values`). However, it doesn't support passing multiple separate arrays as arguments directly, such as `difference([1, 2, 3, 4], [2, 3], [1, 2])`. 

### Proposed Solution
I propose modifying the function signature to use the rest parameter syntax (`...values`). By doing so, the function can handle test cases like `difference([1, 2, 3, 4], [2, 3], [1, 2])`.

## Code you used to submit (where relevant)

```js
/**
 * @param {Array<*|Array>} value
 * @return {Array}
 */
export default function difference(array, ...values) {
  const result = [];

  // Create a set of all the values in the values arrays
  const valuesSet = new Set(values.flat());

  for (let i = 0; i < array.length; i++) {
    const value = array[i];
    // Check if the value is in the values set
    if (!valuesSet.has(value) && !(value === undefined && !(i in array))) {
      result.push(value);
    }
  }

  return result;
}
```

**Comment by yangshun** [comment]
Thanks for the suggestion but we want to keep the question simple as it's "Easy" difficulty so we'll stick with just 2 arrays.
