### ISSUE TITLE
Issue with Throttle

### ISSUE THREAD

**Issue by mhughdo** [greatfrontend/greatfrontend#59]
## Your GreatFrontEnd account email (optional)

mhughdo@gmail.com 

## Problematic section

- [ ] Question Description
- [ ] Question Skeleton
- [ ] Question Solution
- [x] Test Cases (Missing/Incorrect/Unclear)

## Type of question

- [x] JavaScript
- [ ] User Interface
- [ ] System Design
- [ ] Quiz

## Code you used to submit (where relevant)

```js
/**
 * @callback func
 * @param {number} wait
 * @return {Function}
 */
export default function throttle(func, wait) {
  let lastExecutionTime = 0

  return function(...args) {
    if (Date.now() - lastExecutionTime <= wait) {
      return
    }
    lastExecutionTime = Date.now()
    func.apply(this, args)
  }
}
```

## Expected behavior vs Actual behavior (where relevant)

The test result is not consistent, I used the above code to submit, and sometimes it failed but sometimes it passed.

## Screenshots (where relevant)

<img width="569" alt="image" src="https://github.com/greatfrontend/greatfrontend/assets/15611134/1d63b6bb-8a23-462e-ac24-b5c36e190ac0">

<img width="569" alt="image" src="https://github.com/greatfrontend/greatfrontend/assets/15611134/d7c9a184-7e1b-4a81-8640-a34daafa4a45">

**Comment by yangshun** [comment]
This is version blocks the main thread which is incorrect and bad. You should be using `setTimeout`.
