### ISSUE TITLE
Issue with Data Selection

### ISSUE THREAD

**Issue by elias-pap** [greatfrontend/greatfrontend#62]
## Your GreatFrontEnd account email (optional)

eliaspap@pm.me 

## Problematic section

- [x] Question Description
- [ ] Question Skeleton
- [ ] Question Solution
- [ ] Test Cases (Missing/Incorrect/Unclear)

## Type of question

- [x] JavaScript
- [ ] User Interface
- [ ] System Design
- [ ] Quiz

## Describe the issue

User 1 does not use a dumbbell but the example return value contains one.

```
selectData(sessions, { merge: true });
// [
//   { user: 8, duration: 50, equipment: ['bench'] },
//   { user: 1, duration: 10, equipment: ['dumbbell'] }, <-- 'dumbbell' should be 'barbell' here
//   { user: 7, duration: 450, equipment: ['bike', 'dumbbell', 'kettlebell'] },
//   { user: 2, duration: 400, equipment: ['bike', 'treadmill'] },
// ];
```

**Comment by yangshun** [comment]
Fixed!
