### ISSUE TITLE
Issue with Table of Contents

### ISSUE THREAD

**Issue by elias-pap** [greatfrontend/greatfrontend#63]
## Your GreatFrontEnd account email (optional)

eliaspap@pm.me 

## Problematic section

- [x] Question Description
- [ ] Question Skeleton
- [ ] Question Solution
- [ ] Test Cases (Missing/Incorrect/Unclear)

## Type of question

- [x] JavaScript
- [ ] User Interface
- [ ] System Design
- [ ] Quiz

## Describe the issue

```
const doc = new DOMParser().parseFromString(
  `<!DOCTYPE html>
  <body>
    <h1>Heading1</h1>
    <h2>Heading2a</h2>
    <h2>Heading2b</h2>
    <h3>Heading3a</h3>
    <h3>Heading3b</h3>
    <h4>Heading4</h3>  <-- should be </h4> here
    <h2>Heading2c</h2>
  </body>`,
  'text/html',
);
```

**Comment by yangshun** [comment]
Fixed!
