### ISSUE TITLE
Issue with Deep Equal

### ISSUE THREAD

**Issue by Xapuu** [greatfrontend/greatfrontend#68]
## Your GreatFrontEnd account email (optional)

xapu.ivanov@gmail.com 

## Problematic section

- [ ] Question Description
- [ ] Question Skeleton
- [ ] Question Solution
- [ ] Test Cases (Missing/Incorrect/Unclear)
- [x] Other

## Type of question

- [x] JavaScript
- [ ] User Interface
- [ ] System Design
- [ ] Quiz

## Describe the issue

I'm getting the following error in the browser console : 
`ModuleNotFoundError: Could not find module in path: './solution-alt' relative to '/index.test.ts'`, which i assume causes the "debug" console that is integrated to crash.

The issue I'm facing is that the debug console doesn't work. The console doesn't print any results, beside some internal (related to the sandbox) error messages.

## Code you used to submit (where relevant)

```js
/**
 * @param {*} valueA
 * @param {*} valueB
 * @return {boolean}
 */
// https://www.greatfrontend.com/questions/javascript/deep-equal?list=one-week
export default function deepEqual(valueA, valueB) {
  const typeOfA = typeof valueA;
  const typeOfB = typeof valueB;
  console.log(valueA, valueB , '  <== Root')
  if(typeOfA !== typeOfB){
    return false;
  }

  if(typeOfA === 'string' || typeOfA === 'number' ){
    console.log(valueA === valueB)
    return valueA === valueB;
  }

  if(Array.isArray(valueA)){
    return compareArrays(valueA, valueB)
  }

  if(typeOfA === 'object'){
    return compareObjects(valueA, valueB);
  }

}


function compareArrays(arrA, arrB) {

  const aLength = arrA.length;
  const bLength = arrB.length;

  if(aLength !== bLength){
    return false;
  }

  return !arrA.find((_, index) => !deepEqual(arrA[index], arrB[index]));
}

function compareObjects(objA, objB){
  const aEntries = Object.entries(objA);
  const bEntries = Object.entries(objB);
  if(aEntries.length !== bEntries.length){
    return false;
  }
  return compareArrays(aEntries, bEntries);
}

deepEqual();
console.log(deepEqual(1,1));
console.log(deepEqual(1,1));
```

## Expected behavior vs Actual behavior (where relevant)

The behavior that I expect is to see different logs inside the debug console, produced by the code inserted in the solution

## Screenshots (where relevant)
![image](https://github.com/greatfrontend/greatfrontend/assets/23619201/f86735a6-c318-4986-8992-f39933cb050c)
![image](https://github.com/greatfrontend/greatfrontend/assets/23619201/777e32a7-bcd8-4ada-9b29-aa52fdb11d6a)

## Anything else?
Tested on : 
  * Chrome Version 115.0.5790.110 (Official Build) (64-bit)
  * Brave 1.56.14 (which uses Upgraded Chromium to 115.0.5790.114)

**Comment by yangshun** [comment]
This has been fixed!
