### ISSUE TITLE
Issue with Drop Right While

### ISSUE THREAD

**Issue by indrajitbnikam** [greatfrontend/greatfrontend#69]
## Your GreatFrontEnd account email (optional)

indrajitbnikam@gmail.com 

## Problematic section

- [ ] Question Description
- [ ] Question Skeleton
- [ ] Question Solution
- [X] Test Cases (Incorrect)

## Type of question

- [X] JavaScript
- [ ] User Interface
- [ ] System Design
- [ ] Quiz

## Describe the issue

The following test case is failing.

> dropRightWhile > required arguments are passed > array is passed

## Code you used to submit (where relevant)

```ts
export default function dropRightWhile<T>(
  array: Array<T>,
  predicate: (value: T, index: number, array: Array<T>) => boolean,
): Array<T> {
  let tempArr = [...array];

  let predicateTrue = true;
  while (tempArr.length > 0 && predicateTrue) {
    const lastIndex = tempArr.length - 1;
    if (predicate(tempArr[lastIndex], lastIndex, tempArr)) {
      tempArr.splice(lastIndex);
    } else {
      predicateTrue = false;
    }
  }

  return tempArr;
}
```

## Expected behavior vs Actual behavior (where relevant)

As per the logic, 4th element in the array should stay in the returned value as `5 > arr.length (i.e. 4)`

**Comment by yangshun** [comment]
Clarified problem in the description
