### ISSUE TITLE
Feature Request  -> View Test Cases

### ISSUE THREAD

**Issue by kmanadkat** [greatfrontend/greatfrontend#7]
## Your GreatFrontEnd account email (optional)

kmanadkat@gmail.com

## Problematic section

- [ ] Question Description
- [ ] Question Skeleton
- [ ] Question Solution
- [x] Test Cases (Missing/Incorrect/Unclear)

## Type of question

- [x] JavaScript
- [ ] User Interface
- [ ] System Design
- [ ] Quiz

## Describe the issue

To understand why my solution is failing or not accepted, as a student I would like to know the test cases. I understand new feature development can take time so for time being could you please show me the test cases for `Array.prototype.filter` coding question?

## Code you used to submit (where relevant)

```js
Array.prototype.myFilter = function (callbackFn, thisArg) {
  const result = []
  const arr = Array.isArray(thisArg) ? thisArg : this
  const len = arr.length

  for(let i = 0; i < len; i++) {
    const ele = arr[i]
    if(ele !== undefined && callbackFn(ele, i, arr)) {
      result.push(ele)
    }
  }
  return result
};
```

## Expected behavior vs Actual behavior (where relevant)

Expecting all test cases to pass, 
Actual behaviour: one of the test cases failing

## Screenshots (where relevant)

<img width="2056" alt="Screenshot 2022-11-29 at 10 11 40 AM" src="https://user-images.githubusercontent.com/25281055/204440940-20ae073a-f81e-4066-8c9f-29a0b0aadbb5.png">

**Comment by gfeeng** [comment]
Hi @kmanadkat, for the Array method questions, all the callbacks should have the `this` argument explicitly passed in either via `.call()` or `.apply()` instead of calling the function directly. You just have to change how `callbackFn` is being called.

Here's a modified version which passes the test cases:

```js
Array.prototype.myFilter = function (callbackFn, thisArg) {
  const result = []
  const arr = Array.isArray(thisArg) ? thisArg : this
  const len = arr.length

  for(let i = 0; i < len; i++) {
    const ele = arr[i]
    // Change the way callbackFn is called 
    if(ele !== undefined && callbackFn.call(thisArg, ele, i, arr)) {
      result.push(ele)
    }
  }
  return result
};
```

**Comment by kmanadkat** [comment]
Hi @gfeeng , it is very nice to get prompt help :) 

I want to know why it works with the modification?

Also I am searching examples all over the google where `thisArg` is used, unfortunately I could not find any. Also most implementations of custom `filter()` method on blogs is not as complete as in GreatFrontend.

I am kind of stuck here. Please help me with the test cases and used.

**Comment by gfeeng** [comment]
> I want to know why it works with the modification?

When functions are called, the `this` value within it is determined by the object that is calling the function. By doing `callbackFn()`, the `this` value refers to the `global` object. The `Array.prototype.filter` method allows users to define the `this` to be used within `callbackFn`s, and using `.call()` or `.apply()` to call your functions is the most straightforward way to call functions with `this` bound to something.

> Also most implementations of custom filter() method on blogs is not as complete as in GreatFrontend.

This is the value of GreatFrontEnd :)

> I am kind of stuck here. Please help me with the test cases used.

Here you go:

```js
const isThisProductEven = function (element) {
  return (element * this) % 2 === 0;
};
const isThisProductEvenArrowFn = (element) => (element * this) % 2 === 0;

test('uses this argument', () => {
  expect([1, 2, 3, 4].myFilter(isThisProductEven)).toEqual([]);
  expect([1, 2, 3, 4].myFilter(isThisProductEven, 10)).toEqual([1, 2, 3, 4]);
  expect([1, 2, 3, 4].myFilter(isThisProductEven, 9)).toEqual([2, 4]);
  expect([1, 2, 3, 4].myFilter(isThisProductEvenArrowFn)).toEqual([]);
  expect([1, 2, 3, 4].myFilter(isThisProductEvenArrowFn, 10)).toEqual([]);
  expect([1, 2, 3, 4].myFilter(isThisProductEvenArrowFn, 9)).toEqual([]);
});
```

**Comment by kmanadkat** [comment]
Thanks @gfeeng

**Comment by kmanadkat** [comment]
@gfeeng it seems you guys added Test Cases tab, thank you so much!!

I was coding debounce function & somehow last test case was not passing. I saw the test case & it helped me fully understand few things, which I could have missed if I had just looked at the solution & pasted it > Submit.

<img width="684" alt="Screenshot 2023-01-24 at 11 33 06 PM" src="https://user-images.githubusercontent.com/25281055/214372408-63c25d86-c432-4c39-b4ce-19eb1bccae81.png">

**Comment by gfeeng** [comment]
@kmanadkat That's great to hear! Thanks for the positive affirmation 😃
