### ISSUE TITLE
Issue with Deep Equal

### ISSUE THREAD

**Issue by tschneit717** [greatfrontend/greatfrontend#72]
## Your GreatFrontEnd account email (optional)

tschneit717@gmail.com

## Problematic section

- [ ] Question Description
- [ ] Question Skeleton
- [ ] Question Solution
- [X] Test Cases (Missing/Incorrect/Unclear)

## Type of question

- [X] JavaScript
- [ ] User Interface
- [ ] System Design
- [ ] Quiz

## Describe the issue

Unable to test any submissions, all code fails upon clicking submit

## Code you used to submit (where relevant)

```js
/**
 * @param {*} valueA
 * @param {*} valueB
 * @return {boolean}
 */
export default function deepEqual(valueA, valueB) {
  console.log(valueA, valueB)
  // throw 'Not implemented!';
}
```

## Expected behavior vs Actual behavior (where relevant)

I would expect my code to run and run the tests provided

## Screenshots (where relevant)

![Screenshot 2023-08-16 at 8 25 49 PM](https://github.com/greatfrontend/greatfrontend/assets/24719866/477fc628-70bb-4f8b-a4a4-47af99fd2b41)

**Comment by yangshun** [comment]
This has been fixed in the new coding workspace!
