### ISSUE TITLE
Minified React error #418

### ISSUE THREAD

**Issue by rajanshresth** [greatfrontend/greatfrontend#73]
<img width="888" alt="image" src="https://github.com/greatfrontend/greatfrontend/assets/76089000/e4536301-e025-4d35-a3d1-2b78d1efc739">
<img width="420" alt="image" src="https://github.com/greatfrontend/greatfrontend/assets/76089000/bded2198-eab1-4bb3-afd7-dd2d0ab25270">

**Comment by gfeeng** [comment]
You're probably using a browser extension that is messing with the DOM. Check if you have any extensions for copying and pasting code.
