### ISSUE TITLE
Issue with Count By

### ISSUE THREAD

**Issue by vaibhavyadaram** [greatfrontend/greatfrontend#75]
## Problematic section

- [ ] Question Description
- [ ] Question Skeleton
- [ ] Question Solution
- [x] Test Cases (Missing/Incorrect/Unclear)

## Type of question

- [x] JavaScript
- [ ] User Interface
- [ ] System Design
- [ ] Quiz

## Describe the issue

Any code submitted for Count By won't run. Console says it cannot find the tests. I tried running my solution, the provided solution and simply logging a message, it continues to say "Evaluating tests against code"

<img width="1005" alt="Screen Shot 2023-09-02 at 5 25 55 PM" src="https://github.com/greatfrontend/greatfrontend/assets/13441862/85e3c38a-ae05-4722-98b8-cf6b3c45409b">

<img width="348" alt="Screen Shot 2023-09-02 at 5 26 01 PM" src="https://github.com/greatfrontend/greatfrontend/assets/13441862/f58da4e1-ff01-40c4-b99b-f7680ef1b17a">

**Comment by yangshun** [comment]
This has been fixed
