### ISSUE TITLE
Add a simpler solution for Difference question

### ISSUE THREAD

**Issue by dolfbarr** [greatfrontend/greatfrontend#76]
## Your GreatFrontEnd account email (optional)

mail@dolf.me

## Problematic section

- [ ] Question Description
- [ ] Question Skeleton
- [x] Question Solution
- [ ] Test Cases (Missing/Incorrect/Unclear)

## Type of question

- [x] JavaScript
- [ ] User Interface
- [ ] System Design
- [ ] Quiz

## Describe the issue

Difference question can be solved in a more simple way, which can be mentioned similar to a simpler solution for Compact question

## Code you used to submit (where relevant)

```js
/**
 * @param {Array} array - Array from which different elements are to be removed.
 * @param {Array} values - Array of values that are to be removed from the original array.
 * @return {Array} Returns filtered array.
 */
export default function difference(array, values) {
  const valuesSet = new Set(values)
  return array.filter(value => !valuesSet.has(value))
}
```

**Comment by jgoerner** [comment]
Nice one. I was thinking about the following (which would mean we don't even have to create new `Set` objects):

```typescript
export default function difference(array, values) {
  return array.filter(value => !values.includes(value))
}
```

**Comment by yangshun** [comment]
@weiquu please help to add in these alternative solutions
