### ISSUE TITLE
Issue with Intersection With

### ISSUE THREAD

**Issue by obssesso** [greatfrontend/greatfrontend#81]
## Your GreatFrontEnd account email (optional)

serhat.sen38@gmail.com

## Problematic section

- [ ] Question Description
- [ ] Question Skeleton
- [X] Question Solution
- [ ] Test Cases (Missing/Incorrect/Unclear)

## Type of question

- [X] JavaScript
- [ ] User Interface
- [ ] System Design
- [ ] Quiz

## Describe the issue

Solution description to the problem "Intersection With" seems to have been copy & pasted form "Intersection By"

## Expected behavior vs Actual behavior (where relevant)

The solution first slices the array to then iterate over the values of the first array via "filter". For every value in the firstArray it then checks whether in "every" other array there is "some" (at least 1) value so that the comparator function returns true.

## Screenshots (where relevant)

![image](https://github.com/greatfrontend/greatfrontend/assets/122223376/cdb4d5ea-25ad-40e8-828b-1e787dc7d4d1)

**Comment by weiquu** [comment]
Thanks for the catch, have made a fix updating the solution description!
