### ISSUE TITLE
Issue with Like Button

### ISSUE THREAD

**Issue by hyfyn** [greatfrontend/greatfrontend#82]
## Your GreatFrontEnd account email (optional)

matt@hyfyn.com 

## Problematic section

- [ ] Question Description
- [ ] Question Skeleton
- [x] Question Solution
- [ ] Test Cases (Missing/Incorrect/Unclear)

## Type of question

- [ ] JavaScript
- [x] User Interface
- [ ] System Design
- [ ] Quiz

## Describe the issue

The Error message is not displaying when the fetch request fails.

## Code you used to submit (where relevant)

```js
if (!response.ok) {
        const res = await response.json();
        setErrorMessage(res.message);
        return;
}
```

## Expected behavior vs Actual behavior (where relevant)

When the api returns an error the `res.message` is displayed

**Comment by gfeeng** [comment]
This has been fixed!
