### ISSUE TITLE
The solution doesn't pass all submissions tests and is not displayed in the submissions (Issue with Drop Right While)

### ISSUE THREAD

**Issue by p0stw3b** [greatfrontend/greatfrontend#86]
## Problematic section

- [ ] Question Description
- [ ] Question Skeleton
- [ ] Question Solution
- [x] Test Cases (Missing/Incorrect/Unclear)

## Type of question

- [x] JavaScript
- [ ] User Interface
- [ ] System Design
- [ ] Quiz

## Describe the issue

After sending a solution, it was not displayed in the submissions and didn't pass all submissions tests.

## Code you used to submit (where relevant)

```ts
/**
 * @param {Array} array - The array to iterate over.
 * @param {Function} predicate - The function invoked per iteration.
 * @return {Array} Returns the slice of `array`.
 */
export default function dropRightWhile(array, predicate) {
  let index = array.length - 1;

  while (index >= 0 && predicate(array[index], index, array)) {
    index--;
  }

  return array.slice(0, index + 1);
}
```

## Expected behavior vs Actual behavior (where relevant)

A: The solution doesn't pass all submissions tests and is not displayed in the Submissions
E: The solution passes all submissions tests and is displayed in the Submissions

**Comment by gfeeng** [comment]
There was a problem with the test runner. We've fixed this!
