### ISSUE TITLE
Not Able to Post Solutions

### ISSUE THREAD

**Issue by likendev** [greatfrontend/greatfrontend#89]
## Your GreatFrontEnd account email (optional)

likendev@gmail.com

## Problematic section

Section to post our solutions.

## Describe the issue

When trying to post our solutions to the community section, it encountered error:

```json
[
    {
        "error": {
            "message": "\nInvalid `prisma.questionJavaScriptCommunitySolution.create()` invocation:\n\n\nThe table `public.QuestionJavaScriptCommunitySolution` does not exist in the current database.",
            "code": -32603,
            "data": {
                "code": "INTERNAL_SERVER_ERROR",
                "httpStatus": 500,
                "path": "questionCommunitySolution.javaScriptAdd"
            }
        }
    }
]
```

## Expected behavior vs Actual behavior (where relevant)

Expecting to be able to post the solutions

## Screenshots (where relevant)

![image](https://github.com/greatfrontend/greatfrontend/assets/15458805/7a91b59c-adb4-4a12-bacd-25c49f085819)

**Comment by yangshun** [comment]
Hi this feature is not yet launched
