### ISSUE TITLE
Issue with JavaScript question Submissions 

### ISSUE THREAD

**Issue by jayakirtani** [greatfrontend/greatfrontend#92]
## Problematic section

- [ ] Question Description
- [ ] Question Skeleton
- [ ] Question Solution
- [ ] Test Cases (Missing/Incorrect/Unclear)
- [x] Submissions

## Type of question

- [x] JavaScript
- [ ] User Interface
- [ ] System Design
- [ ] Quiz

## Describe the issue
If I have multiple submission for a question, I am not able to view specific submission. On clicking any submission, it always shows me the first submitted solution.

## Expected behavior vs Actual behavior (where relevant)

In case of multiple submissions, I should be able view all submitted solutions. I want to be able to revisit the solutions I created in future.

**Comment by yangshun** [comment]
Hi we need more information as we're unable to reproduce the issue. Please check your Discord DM

**Comment by yangshun** [comment]
Reproducible on Safari. This is a CSS bug where the last item's div covers the whole panel, as a result clicking anywhere within the panel will result with clicking on the last div.

@weiquu can you help look into this?
