### ISSUE TITLE
Issue with Promise.allSettled

### ISSUE THREAD

**Issue by nikita-savkin** [greatfrontend/greatfrontend#93]
## Your GreatFrontEnd account email (optional)

no.colour.you.like@gmail.com

## Problematic section

- [] Question Description
- [] Question Skeleton
- [x] Question Solution
- [ ] Test Cases (Missing/Incorrect/Unclear)

## Type of question

- [x] JavaScript
- [ ] User Interface
- [ ] System Design
- [ ] Quiz

## Describe the issue

The issue lies in the provided solution for the `promiseAllSettled` function, where a `forEach` loop is used to handle asynchronous operations. The `forEach` loop does not wait for asynchronous operations to complete, which may lead to incorrect results.

## Code you used to submit (where relevant)

```
/**
 * @param {Array<*|Array>} iterable
 * @return {Array}
 */
export default async function promiseAllSettled(iterable) {
  const results = [];

  for await (const item of iterable) {
    try {
      const fulfilledData = {
        status: 'fulfilled',
        value: null
      }

      if (typeof item === 'function') {
        const args = item.agruments;
        const response = await item.apply(this, args);
        fulfilledData.value = response;
      } else {
        fulfilledData.value = item;
      }

      results.push(fulfilledData);
    } catch (err) {
      const rejectedData = {
        status: 'rejected',
        reason: err
      }

      results.push(rejectedData);
    }
  }

  return results;
}
```

## Expected behavior vs Actual behavior (where relevant)

Initial forEach Implementation:
Expected Behavior:
Asynchronously iterate over each item in the iterable.
For each item, await its completion and construct a corresponding result object.
Once all asynchronous operations are complete, resolve the outer Promise with an array of result objects.
Actual Behavior:
The forEach loop initiates all asynchronous operations concurrently without waiting for their completion.
The resolve(results) statement is reached before the asynchronous operations have finished.
The final state of the results array might be incomplete or contain incorrect values due to the asynchronous nature of the operations.

Corrected for...of Loop Implementation:
Expected Behavior:
Asynchronously iterate over each item in the iterable.
For each item, await its completion and construct a corresponding result object.
Ensure each asynchronous operation completes before moving on to the next iteration.
Once all asynchronous operations are complete, resolve the outer Promise with an array of result objects.
Actual Behavior:
The for...of loop ensures a more controlled and sequential execution of asynchronous operations.
Each iteration waits for the asynchronous operation to complete before moving on to the next one.
The resolve(results) statement is reached only after all asynchronous operations have finished.
The results array is correctly populated with the expected values, providing a more reliable and predictable outcome.

## Anything else?

If we want to execute await calls in series, we have to use a for-loop (or any loop without a callback).
Don’t ever use await with forEach. Use a for-loop (or any loop without a callback) instead.

**Comment by weiquu** [comment]
Hi @nikita-savkin, I'm not sure if the current solution actually gives incorrect results like you say.

My understanding is that it does not resolve until all the async operations are complete, because of these lines (within the `forEach` callback):
```
pending -= 1;
if (pending === 0) {
  resolve(results);
}
```

Hence, we won't run into the case where the resolve statement is reached before the async operations are finished; if at least 1 has not finished, `pending` will be greater than 0, so the resolve statement is not called. (Not sure if there might be some race conditions here.)

Since you mention that the current solution might lead to incorrect results, could you provide an example test case where that happens? I've tried a couple but haven't found any yet. Many thanks! That would greatly help in refining the solution.

**Comment by yangshun** [comment]
The official solution is intended, the promises should not be settled concurrently.
