### ISSUE TITLE
Typo in "questions to ask" in the behavioral interview guidebook

### ISSUE THREAD

**Issue by xming13** [greatfrontend/greatfrontend#94]
## Your GreatFrontEnd account email (optional)

tanweiseng13@gmail.com 

## Problematic section

- [ ] Question Description
- [ ] Question Skeleton
- [ ] Question Solution
- [ ] Test Cases (Missing/Incorrect/Unclear)

## Type of question

- [ ] JavaScript
- [ ] User Interface
- [ ] System Design
- [ ] Quiz

## Describe the issue

There is a typo in the answer to ["Can you show me examples of projects I'd be working on and the technologies I will use? Will I be maintaining projects or building from scratch?"](https://www.greatfrontend.com/behavioral-interview-guidebook/questions-to-ask#can-you-show-me-examples-of-projects-id-be-working-on-and-the-technologies-i-will-use-will-i-be-maintaining-projects-or-building-from-scratch)

"grown up" should be "ground up".

## Expected behavior vs Actual behavior (where relevant)

Actual: "In general, having the opportunity to build products from **grown up** could be a better learning opportunity than doing small, incremental features."

Expected: "In general, having the opportunity to build products from **ground up** could be a better learning opportunity than doing small, incremental features."

## Screenshots (where relevant)

<img width="694" alt="image" src="https://github.com/greatfrontend/greatfrontend/assets/6182649/4fde9fd0-5814-4adc-86df-11e9a83e8599">

**Comment by feilinlp** [comment]
Thank you for pointing it out! We have fixed it and it'll be deployed soon.
