### ISSUE TITLE
Issue with Data Selection

### ISSUE THREAD

**Issue by santoshjoseph99** [greatfrontend/greatfrontend#95]
## Your GreatFrontEnd account email (optional)

santoshjoseph73@gmail.com 

## Problematic section

- [ ] Question Description
- [ ] Question Skeleton
- [ ] Question Solution
- [X] Test Cases (Missing/Incorrect/Unclear)

## Type of question

- [X] JavaScript
- [ ] User Interface
- [ ] System Design
- [ ] Quiz

## Describe the issue
Seems like my solution is correct. I copied and ran it separately and I output the right answer.

## Code you used to submit (where relevant)

```js
/type Session = { user: number; duration: number; equipment: Array<string> };
type Options = {
  user?: number;
  minDuration?: number;
  equipment?: Array<string>;
  merge?: boolean;
};

function selectData(
  sessions: Array<Session>,
  options?: Options,
): Array<Session> {

   if(!options) {
    return sessions;
   }
   const merged = (options.merge === true) ? sessions.reduce((prev, curr) => {
    const foundIdx = prev.findIndex(x => x.user === curr.user);
    if(foundIdx === -1) {
      prev.push(curr);
      return prev;
    }
    const found = prev[foundIdx]
    found.duration += curr.duration;
    for(let c = 0; c < curr.equipment.length; c++){
      for(let f = 0; f < found.equipment.length; f++) {
        if(!found.equipment.includes(curr.equipment[c])) {
          found.equipment.push(curr.equipment[c]);
        }
      }
    }
    found.equipment.sort();
    prev.splice(foundIdx, 1);
    prev.push(found);
    return prev;
   }, [] as Array<Session>) : sessions;
  
   const output = merged.reduce((prev, curr) => {
    let added = false;
    if(options.user) {
      if(curr.user === options.user) prev.push(curr)
      added = true;
    }
    if(options.minDuration && !added) {
      if(curr.duration >= options.minDuration ) prev.push(curr)
      added = true;
    }
    if(options.equipment && !added) {
      for(let i = 0; i < options.equipment.length; i++) {
        if(curr.equipment.includes(options.equipment[i])){
          prev.push(curr);
          break;
        }
      }
    }
    return prev;
   }, [] as Array<Session>)
 
   return output;
}

```

## Expected behavior vs Actual behavior (where relevant)

the test case:     test('user with multiple sessions', () => {
      expect(selectData(dataSmall, { user: 2 })).toEqual([
        { user: 2, duration: 200, equipment: ['treadmill'] },
        { user: 2, duration: 200, equipment: ['bike'] },
      ]);
    });

this is what I my outputs (and what I expect):
 [{
  "user": 2,
  "duration": 200,
  "equipment": [
    "treadmill"
  ]
}, {
  "user": 2,
  "duration": 200,
  "equipment": [
    "bike"
  ]
}] 

## Screenshots (where relevant)
This is the test failure:
<img width="566" alt="Screenshot 2023-12-10 at 7 19 45 PM" src="https://github.com/greatfrontend/greatfrontend/assets/461049/cdecbcc5-e17b-4a22-8f48-fc2cd5c3a916">

**Comment by yangshun** [comment]
You shouldn't mutate the input array as it affects the cases used for subsequent tests. We've modified our test cases to guard against this.
