### ISSUE TITLE
In Range Test Case Description

### ISSUE THREAD

**Issue by BryanAM** [greatfrontend/greatfrontend#96]
## Issue Description
There is a bit of semantic confusion with the test case and the description of the problem. 

- [ ] Question Description
- [ ] Question Skeleton
- [ ] Question Solution
- [ X ] Test Cases (Missing/Incorrect/Unclear)

## Type of question

- [ X ] JavaScript
- [ ] User Interface
- [ ] System Design
- [ ] Quiz

## Describe the issue

In the In Range practice problem the problem states:

>  If end is not specified, the start argument becomes end and start is set to 0.

However, the following test semantically, not logically, contradicts the description. 

```javascript
  test('only `end` specified', () => {
    expect(inRange(3, 5)).toBe(true);
    expect(inRange(6, 5)).toBe(false);
  });

```

## Expected behavior vs Actual behavior (where relevant)

Actual test case descriptor: 'only `end` specified'
Expected test case descriptor: 'only `start` specified'

## Screenshots (where relevant)

<img width="747" alt="Screenshot 2023-12-12 at 08 57 57" src="https://github.com/greatfrontend/greatfrontend/assets/32301578/25fb57a6-d53c-4f1e-8f32-914c7b05d4bb">

## Anything else?

No issue with the execution of the code. Simply a semantic suggestion to improve clarity. Although the logical implication is end becomes start and start becomes zero, I suggest we follow the pattern of what the description in the problem states.

**Comment by weiquu** [comment]
Thanks! Have made a fix
