### ISSUE TITLE
Issue with Find Last Index

### ISSUE THREAD

**Issue by dannyhkim** [greatfrontend/greatfrontend#98]
## Your GreatFrontEnd account email (optional)

dannykim200@gmail.com 

## Problematic section

- [x] Question Description
- [ ] Question Skeleton
- [ ] Question Solution
- [ ] Test Cases (Missing/Incorrect/Unclear)

## Type of question

- [x] JavaScript
- [ ] User Interface
- [ ] System Design
- [ ] Quiz

## Describe the issue

One of the examples given in the description is incorrect I believe.

## Code you used to submit (where relevant)

```js
/**
 * @param {Array<*|Array>} value
 * @return {Array}
 */
export default function flatten(value) {
  // Your code here.
}
```

## Expected behavior vs Actual behavior (where relevant)

```
const arr = [5, 4, 3, 2, 1];
// Search leftwards from index that's already out of bounds,
// which will always result in -1.
findLastIndex(arr, (num) => num > 2, -10); // => -1
```
The edge case above should result in '0', not '-1'. A negative index of -10 should mean that we begin the array scan at index 0, and since 5 > 2, the predicate function should be satisfied and a result of 0 should be returned. 

## Screenshots (where relevant)

<img width="1020" alt="Screenshot 2023-12-19 at 11 25 20 PM" src="https://github.com/greatfrontend/greatfrontend/assets/43249425/5a49e317-24ef-4f37-8203-13584236c110">

I ran the example as a test case and it verified that the result should be 0.

**Comment by weiquu** [comment]
Thanks! Have made a fix
