### ISSUE TITLE
Fix test with data selection

### ISSUE THREAD

**Issue by IsenrichO** [greatfrontend/greatfrontend#99]
## Problematic section

- [x] Question Description
- [ ] Question Skeleton
- [ ] Question Solution
- [ ] Test Cases (Missing/Incorrect/Unclear)

## Type of question

- [x] JavaScript
- [ ] User Interface
- [ ] System Design
- [ ] Quiz

## Describe the issue

Several of the sample cases provided for the `selectData` function in the [Data Selection](https://www.greatfrontend.com/questions/javascript/data-selection) challenge are wrong. The sample cases show how the expected output of the `selectData` function based on the provided sample data. Some of the sample cases reference this session

```js
{ user: 7, duration: 150, equipment: ['dumbbell', 'kettlebell'] },
```

however, the `equipment` listed for that session in the sample data is just `dumbbell`.

## Expected behavior vs Actual behavior (where relevant)

Correct sample case should be:
```js
[
  { user: 7, duration: 150, equipment: ['dumbbell'] },
  { user: 7, duration: 100, equipment: ['bike', 'kettlebell'] },
  { user: 7, duration: 200, equipment: ['bike'] },
  { user: 2, duration: 200, equipment: ['bike'] },
];

```

## Screenshots (where relevant)

Provided sample data:
<img width="976" alt="Screen Shot 2023-12-27 at 10 47 14" src="https://github.com/greatfrontend/greatfrontend/assets/11098273/a8c9e257-6361-41e0-b987-a2ab72e6aa5d">

One of the incorrect sample cases:
<img width="745" alt="Screen Shot 2023-12-27 at 10 46 30" src="https://github.com/greatfrontend/greatfrontend/assets/11098273/4e137c5c-a931-4343-8d27-3f09fa5a89d0">

## Anything else?

Quickest fix is probably to just update the sample data for that session to include `kettlebell`.

**Comment by yangshun** [comment]
Thank you, we've fixed it
